modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issues}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${toml_name}"
#updateJSONURL=""
displayURL="${mod_url}"
logoFile="${mod_logo}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.bossutils]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.bossutils]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_versionRange}"
    ordering="NONE"
    side="BOTH"
